use crate::http::{Request, Response, StatusCode};
use std::fs;
use std::path::Path;
use std::sync::{Arc, Mutex};

/// Shared connection counter for tracking active connections
#[derive(Clone)]
pub struct ConnectionCounter {
    count: Arc<Mutex<u32>>,
}

impl ConnectionCounter {
    pub fn new() -> Self {
        ConnectionCounter {
            count: Arc::new(Mutex::new(0)),
        }
    }

    pub fn increment(&self) {
        let mut count = self.count.lock().unwrap();
        *count += 1;
    }

    pub fn get_count(&self) -> u32 {
        *self.count.lock().unwrap()
    }
}

impl Default for ConnectionCounter {
    fn default() -> Self {
        Self::new()
    }
}

/// Home page handler
pub fn home_handler(_req: &Request) -> Response {
    let html = r#"
<!DOCTYPE html>
<html>
<head>
    <title>Rust HTTP Server</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        h1 { color: #333; }
        .card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin: 20px 0;
        }
        code {
            background: #f0f0f0;
            padding: 2px 6px;
            border-radius: 3px;
        }
        a {
            color: #0066cc;
            text-decoration: none;
        }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>🦀 Multithreaded HTTP Server</h1>

    <div class="card">
        <h2>Welcome!</h2>
        <p>This is a simple HTTP server built with Rust, demonstrating:</p>
        <ul>
            <li>Thread pool for concurrent request handling</li>
            <li>Custom HTTP parsing (no external dependencies)</li>
            <li>Route matching and handlers</li>
            <li>Thread-safe state management</li>
        </ul>
    </div>

    <div class="card">
        <h2>Available Routes</h2>
        <ul>
            <li><a href="/">GET /</a> - This page</li>
            <li><a href="/hello">GET /hello</a> - Simple greeting</li>
            <li><a href="/sleep">GET /sleep</a> - Slow endpoint (5s delay)</li>
            <li><a href="/stats">GET /stats</a> - Server statistics</li>
        </ul>
    </div>

    <div class="card">
        <h2>Try It Out</h2>
        <p>Open your terminal and try:</p>
        <pre><code>curl http://localhost:7878/hello</code></pre>
        <pre><code>ab -n 100 -c 10 http://localhost:7878/</code></pre>
    </div>
</body>
</html>
"#;

    Response::new(StatusCode::OK)
        .content_type("text/html")
        .body(html.to_string())
}

/// Hello handler
pub fn hello_handler(_req: &Request) -> Response {
    let html = r#"
<!DOCTYPE html>
<html>
<head>
    <title>Hello from Rust!</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding: 100px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        h1 { font-size: 48px; margin: 0; }
        p { font-size: 24px; }
    </style>
</head>
<body>
    <h1>👋 Hello from Rust!</h1>
    <p>This response was generated by a worker thread.</p>
    <p><a href="/" style="color: white;">← Back to home</a></p>
</body>
</html>
"#;

    Response::new(StatusCode::OK)
        .content_type("text/html")
        .body(html.to_string())
}

/// Slow endpoint that simulates expensive computation
pub fn sleep_handler(_req: &Request) -> Response {
    use std::thread;
    use std::time::Duration;

    println!("Sleeping for 5 seconds...");
    thread::sleep(Duration::from_secs(5));

    Response::new(StatusCode::OK)
        .content_type("text/plain")
        .body("I'm awake now! (slept for 5 seconds)".to_string())
}

/// Stats handler with connection counter
pub fn stats_handler(counter: ConnectionCounter) -> impl Fn(&Request) -> Response {
    move |_req: &Request| {
        let count = counter.get_count();
        let html = format!(
            r#"
<!DOCTYPE html>
<html>
<head>
    <title>Server Stats</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
        }}
        .stat {{
            background: #f0f0f0;
            padding: 20px;
            border-radius: 8px;
            margin: 10px 0;
        }}
        .number {{
            font-size: 48px;
            font-weight: bold;
            color: #0066cc;
        }}
    </style>
</head>
<body>
    <h1>📊 Server Statistics</h1>
    <div class="stat">
        <div class="number">{}</div>
        <p>Total connections handled</p>
    </div>
    <p><a href="/">← Back to home</a></p>
</body>
</html>
"#,
            count
        );

        Response::new(StatusCode::OK)
            .content_type("text/html")
            .body(html)
    }
}

/// Static file handler
pub fn static_file_handler(file_path: &str) -> impl Fn(&Request) -> Response + '_ {
    move |_req: &Request| {
        // Security: prevent directory traversal
        if file_path.contains("..") {
            return Response::new(StatusCode::BadRequest)
                .body("Invalid file path".to_string());
        }

        let full_path = Path::new("static").join(file_path);

        match fs::read_to_string(&full_path) {
            Ok(contents) => {
                // Determine content type from extension
                let content_type = match full_path.extension().and_then(|s| s.to_str()) {
                    Some("html") => "text/html",
                    Some("css") => "text/css",
                    Some("js") => "application/javascript",
                    Some("json") => "application/json",
                    Some("png") => "image/png",
                    Some("jpg") | Some("jpeg") => "image/jpeg",
                    _ => "text/plain",
                };

                Response::new(StatusCode::OK)
                    .content_type(content_type)
                    .body(contents)
            }
            Err(_) => Response::new(StatusCode::NotFound)
                .content_type("text/html")
                .body("<h1>404 - File Not Found</h1>".to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use crate::http::Method;

    fn create_test_request() -> Request {
        Request {
            method: Method::GET,
            path: "/".to_string(),
            version: "HTTP/1.1".to_string(),
            headers: HashMap::new(),
            body: String::new(),
        }
    }

    #[test]
    fn test_home_handler() {
        let req = create_test_request();
        let response = home_handler(&req);
        assert!(response.get_body().contains("Multithreaded HTTP Server"));
    }

    #[test]
    fn test_hello_handler() {
        let req = create_test_request();
        let response = hello_handler(&req);
        assert!(response.get_body().contains("Hello from Rust"));
    }

    #[test]
    fn test_connection_counter() {
        let counter = ConnectionCounter::new();
        assert_eq!(counter.get_count(), 0);

        counter.increment();
        assert_eq!(counter.get_count(), 1);

        counter.increment();
        assert_eq!(counter.get_count(), 2);
    }

    #[test]
    fn test_stats_handler() {
        let counter = ConnectionCounter::new();
        counter.increment();
        counter.increment();

        let handler = stats_handler(counter);
        let req = create_test_request();
        let response = handler(&req);

        assert!(response.get_body().contains("2"));
    }
}
